name: Nodejs Github Action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  #checkout repo 
    - name: Use Nodejs

    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: npm install, build, and test
      run: npm install
    - name: Run test
      run: npm test